config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => 'deeds#index'
  devise_for :users, controllers: {}
  resources :accounts
  resources :deeds do
    resources :comments
  end
end

app/models/account.rb
class Account < ApplicationRecord
  validates_presence_of :username
  has_many :deeds
  has_many :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :deed
  belongs_to :account

  validates :content, :presence => true
end

app/models/deed.rb
class Deed < ActiveRecord::Base
  has_many :comments
  validates :content, :presence => true
  validates :location, :presence => true
  geocoded_by :location
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email
  validates_presence_of :encrypted_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :account
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    current_user
    @account = Account.find(params[:id])
  end

  def new
    current_user
    @account = Account.new
  end

  def create
    current_user
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    if @account.save
      redirect_to account_path(@account)
    else
      render :new
    end
  end

  def edit
    current_user
    @account = Account.find(params[:id])
  end

  def update
    current_user
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to account_path(@account)
    else
      render :edit
    end
  end

private
  def account_params
    params.require(:account).permit(:username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @deed = Deed.find(params[:deed_id])
    @comment = @deed.comments.new
  end

  def create
    current_user
    @deed = Deed.find(params[:deed_id])
    @comment = @deed.comments.new(comment_params)
    @comment.account_id = current_user.account.id
    if @comment.save
      flash[:notice] = "Comment has been added"
      respond_to do |format|
        format.html { redirect_to deed_path(@comment.deed) }
        format.json
      end
    else
      render :new
    end
  end

  def edit
    @deed = Deed.find(params[:deed_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @deed = Deed.find(params[:deed_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment has been updated"
      redirect_to deed_path(@comment.deed)
    else
      render :edit
    end
  end

  def destroy
    @deed = Deed.find(params[:deed_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to deed_path(@deed) }
      format.json
    end
    flash[:notice] = "Comment has been deleted"
  end

  private
  def comment_params
    params.require(:comment).permit(:account_id, :content, :deed_id)
  end
end

app/controllers/deeds_controller.rb
class DeedsController < ApplicationController
  def index
    @deeds = Deed.all
    if current_user
      if current_user.account
        render :index
      else
        redirect_to new_account_path
      end
    else
      redirect_to new_user_registration_path
    end
  end

  def show
    current_user
    @deed = Deed.find(params[:id])
    @hash = Gmaps4rails.build_markers(@deed) do |deed, marker, infowindow|
      marker.lat deed.latitude
      marker.lng deed.longitude
      marker.infowindow deed.location
    end
  end

  def new
    @deed = Deed.new
  end

  def create
    current_user
    @deed = Deed.new(deed_params)
    @deed.account_id = current_user.account.id
    if @deed.save
      flash[:notice] = "Deed has been added"
      redirect_to deeds_path
    else
      render :new
    end
  end

  def edit
    @deed = Deed.find(params[:id])
  end

  def update
    @deed = Deed.find(params[:id])
    if @deed.update(deed_params)
      flash[:notice] = "Deed has been updated"
      redirect_to deeds_path
    else
      render :edit
    end
  end

  def destroy
    @deed = Deed.find(params[:id])
    @deed.destroy
    flash[:notice] = "Deed has been removed"
    redirect_to deeds_path
  end

private
  def deed_params
    params.require(:deed).permit(:content, :location, :account_id, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
  <%= f.label 'username' %>
  <%= f.text_field 'username' %>
  <%= f.submit %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit Profile</h1>

<%= render "form" %>

app/views/accounts/new.html.erb
<h1>New Profile</h1>

<%= render "form" %>

app/views/accounts/show.html.erb
<h1><%= @account.username %></h1>

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@deed, @comment], remote: true do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/comments/destroy.js.erb
$('#delete_comment_<%= @comment.id %>').remove()

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form" %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render "form" %>

app/views/comments/new.js.erb
$("#new_comment").hide().after('<%= j render "form" %>')

app/views/deeds/_form.html.erb
<%= render "layouts/errors", :object => @deed %>

<%= form_for @deed do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.submit %>
<% end %>

app/views/deeds/edit.html.erb
<h1>Edit Deed</h1>

<%= render "form" %>

app/views/deeds/index.html.erb
<h1>Deeds</h1>

<ul>
  <% @deeds.each do |deed| %>
    <li><%= link_to deed.content, deed_path(deed) %></li>
  <% end %>
</ul>

<h1>Karma Score <%= @deeds.length %></h1>

<%= link_to "Record a deed", new_deed_path %>

app/views/deeds/new.html.erb
<% content_for(:title, "Record Deed") %>


<h1>New Deed</h1>

<%= render "form" %>

app/views/deeds/show.html.erb
<% content_for(:title, "Deed") %>

<h1><%= @deed.content %></h1>
<h3><%= @deed.created_at %></h3>
<h3><%= @deed.location %></h3>

<div id="map" style='width: 800px; height: 400px;'></div>

<script type="text/javascript">
  var origin = new google.maps.LatLng(<%= raw @deed.latitude.to_json %>, <%= raw @deed.longitude.to_json %>);
  handler = Gmaps.build('Google', { markers: { clusterer: undefined  } });
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

<% if @deed.comments.any? %>
  <h4>Here are the comments for this deeds:</h4>

  <ul>
    <% @deed.comments.each do |comment| %>
       <li>
        Author: <%= Account.find(comment.account_id).username %>, Content: <%= comment.content %>
        <% if comment.account_id == current_user.account.id %>
          <%= link_to "Edit Comment", edit_deed_comment_path(@deed, comment) %> | <%= link_to "Delete Comment", deed_comment_path(@deed, comment), remote: true, id: "delete_comment", :data => {:confirm => "Delete?", :method => "delete"} %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no comments yet!</p>
<% end %>

<p><%= link_to "Add a comment", new_deed_comment_path(@deed), id: "new_comment", remote: true %></p>

<% if @deed.account_id == current_user.account.id %>
  <p><%= link_to "Edit", edit_deed_path(@deed) %></p>
  <p><%= link_to "Delete", deed_path(@deed), :data => {:confirm => "Positive?", :method => "delete"} %></p>
<% end %>

<p><%= link_to "Home", deeds_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karma Map</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='//maps.google.com/maps/api/js?v=3.exp&key=AIzaSyB016_NNYZtT952q1HzwcHNBDZtg875MoU'></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  </head>

  <body>
    <header>
      <h1>Karma Map</h1>
      <%= link_to "Caleb Stokka", 'https://github.com/stok0102'%>

    </header>
    <ul class="navbar">
      <li class="navbar-link"><%= link_to "Deeds", root_path %></li>
      <li class="navbar-link"><%= link_to "Sign In", user_session_path %></li>
      <% if current_user %>
        <% if current_user.account %>
          <li class="navbar-link"><%= link_to "My Profile", account_path(current_user.account)%></li>
          <li class="navbar-link"><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li class="navbar-link"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class="navbar-link"><%= link_to 'Sign In', user_session_path %></li>
        <% end %>
      <% end %>
    </ul>
    <section>
      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </section>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>